# -*- coding: utf-8 -*-
"""BaselineModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFhHvHOv4ea38jf7nOmY8yQT3SJXMpe5
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

"""# 1. Baseline Model

In this section, we reproduced the baseline model described in the project writeup section 3.3.

## 1.1. Loading the Preprocessed CSV Data
"""

from google.colab import drive
drive.mount('/content/drive')

# 1. Load the CSV files & Preprocess the data
# URLs 2000 from FoxNews, 1805 from NBC
csv_file_path = '/content/drive/MyDrive/CIS5190GroupPJ/headline_dataset.csv'
news_df = pd.read_csv(csv_file_path)
news_df.head()
news_df.info()

news_df.info()

nan_rows = news_df[news_df['headline'].isna()]
print("Page not found urls:", nan_rows)

# drop nan rows
news_df = news_df.dropna(subset=['headline'])
news_df.info()
news_copied_df = news_df.copy()

"""## 1.2 Test Data from the Real World"""

# Pulling the real world URLs + headlines for the external test set

# Fox & NBC: filter only article looking URLs
def is_fox_article_url(url: str) -> bool:
    if "foxnews.com" not in url:
        return False

    # Strip query params and fragments
    url = url.split("?", 1)[0].split("#", 1)[0]

    # Exclude obvious non-article sections
    blacklist_parts = [
        "/video/", "/videos/",
        "/category/",
        "/live/",
        "/shows/",
        "/podcasts/",
        "/media/",
        "/weather/",
        "/about/",
        "/contact/"
    ]
    if any(part in url for part in blacklist_parts):
        return False

    # Require main domain
    if not url.startswith("https://www.foxnews.com"):
        return False

    # Get path portion
    path = url.replace("https://www.foxnews.com", "")
    # e.g. "/us/trump-says-something-important"

    # Require at least section + slug: "/section/slug"
    if path.count("/") < 2:
        return False

    last_segment = path.rstrip("/").split("/")[-1]

    # Article slugs typically have hyphens and are not empty
    if "-" not in last_segment:
        return False

    return True


def is_nbc_article_url(url: str) -> bool:
    if "nbcnews.com" not in url:
        return False

    # Strip query/fragments
    url = url.split("?", 1)[0].split("#", 1)[0]

    blacklist_parts = [
        "/video/",
        "/meet-the-press/",
        "/live/",
        "/weather/",
        "/careers/",
        "/about/"
    ]
    if any(part in url for part in blacklist_parts):
        return False

    if not url.startswith("https://www.nbcnews.com"):
        return False

    path = url.replace("https://www.nbcnews.com", "")

    # At least "/section/slug"
    if path.count("/") < 2:
        return False

    last_segment = path.rstrip("/").split("/")[-1]

    if "-" not in last_segment:
        return False

    return True

import requests
from bs4 import BeautifulSoup

# Fox
def get_fox_article_urls_from_page(page_url, max_links=50):
    resp = requests.get(page_url, timeout=8)
    if resp.status_code != 200:
        return []

    soup = BeautifulSoup(resp.text, "html.parser")
    urls = set()

    for a in soup.find_all("a", href=True):
        href = a["href"]

        # Make relative URLs absolute
        if href.startswith("/"):
            href = "https://www.foxnews.com" + href

        if is_fox_article_url(href):
            urls.add(href)

        if len(urls) >= max_links:
            break

    return list(urls)

# NBC
def get_nbc_article_urls_from_page(page_url, max_links=50):
    resp = requests.get(page_url, timeout=8)
    if resp.status_code != 200:
        return []

    soup = BeautifulSoup(resp.text, "html.parser")
    urls = set()

    for a in soup.find_all("a", href=True):
        href = a["href"]
        if href.startswith("/"):
            href = "https://www.nbcnews.com" + href

        if is_nbc_article_url(href):
            urls.add(href)

        if len(urls) >= max_links:
            break

    return list(urls)

fox_urls_new = get_fox_article_urls_from_page("https://www.foxnews.com/", max_links=50)
nbc_urls_new = get_nbc_article_urls_from_page("https://www.nbcnews.com/", max_links=50)

# check urls correctly pulled
print(fox_urls_new[:])
print(nbc_urls_new[:])

# get headlines from the urls

def normalize_url(url):
    if url.endswith(".print"):
        return url[:-6]
    return url

def scrape_headline(raw_url):
    url = normalize_url(raw_url)
    try:
        resp = requests.get(url, timeout=8)
        if resp.status_code != 200:
            return ""
        soup = BeautifulSoup(resp.text, "html.parser")

        # find fox style
        fox_like = soup.find("h1", class_="headline")
        if fox_like and fox_like.get_text(strip=True):
            return fox_like.get_text(strip=True)

        # any generic style (NBC and else)
        h1 = soup.find("h1")
        if h1 and h1.get_text(strip=True):
            return h1.get_text(strip=True)

        # og as title meta
        og = soup.find("meta", property="og:title")
        if og and og.get("content"):
            return og["content"].strip()

        # title
        title_tag = soup.find("title")
        if title_tag and title_tag.get_text(strip=True):
            return title_tag.get_text(strip=True)

        return ""
    except:
        return ""

web_rows = []

for u in fox_urls_new:
    h = scrape_headline(u)
    if not h:
        continue
    web_rows.append({"url": u, "source": "fox", "headline": h})

for u in nbc_urls_new:
    h = scrape_headline(u)
    if not h:
        continue
    web_rows.append({"url": u, "source": "nbc", "headline": h})

web_df = pd.DataFrame(web_rows)

# sanity check
for i, row in web_df.head(10).iterrows():
    print(row["source"], "→", row["headline"])
    print("  ", row["url"])
    print("-" * 60)

print(web_df["source"].value_counts())

web_df = web_df[web_df["headline"].str.len() > 0].reset_index(drop=True)

X_web = web_df["headline"]
y_web = (web_df["source"] != "fox").astype(int)   # fox=0, nbc=1

# evalute on the baseline model

X_web_vec = baseline_vec.transform(X_web)  # transform ONLY
y_web_pred = baseline_lr.predict(X_web_vec)

# evaluate the model

evaluate_model("Baseline in real world web-data", baseline_lr, y_web, y_web_pred)



"""## 1.3 Bsaeline Model

### 1.3.1 Train & Test (Given)

This is a demonstration of the baseline logistic regression model's performance with the provided code in Section 3.3.
"""

# 2. Split the data into training and testing sets
# (80% train, 20% test)

X = news_copied_df['headline']
y = news_copied_df['source']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
    )


# 3. Convert the labels to binary values (0 for fox, 1 for nbc)
y_train = y_train.apply(lambda x: 0 if x == 'fox' else 1)
y_test = y_test.apply(lambda x: 0 if x == 'fox' else 1)


# 4. Convert the text data to TF-IDF features
vectorizer = TfidfVectorizer(stop_words='english', max_features=100)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)


# 5. Train a Logistic Regression model
LR_model = LogisticRegression(max_iter=100)
LR_model.fit(X_train_tfidf, y_train)


# 6. Make prediction on the test set
y_pred = LR_model.predict(X_test_tfidf)

# Helpfer function for evalutaing the model

def evaluate_model(name, model, y_val, y_pred):

    acc = accuracy_score(y_val, y_pred)
    print(f"\n=== {name} ===")
    print(f"Accuracy: {acc:.4f}")
    print(classification_report(y_val, y_pred))
    return acc, vectorizer, model

# Baseline model accuracy:
evaluate_model("Baseline", LR_model, y_test, y_pred)


## Result provided in Section 3.3
# Accuracy: 0.6649
# Classification Report:
#               precision   recall   f1-score   support
#            0    0.69       0.54      0.60       358
#            1    0.65       0.78      0.71       400
#

"""We see that the baseline model of Logistic Regression is performing at a comparable level to the result provided in the writeup Section 3.3. From here, we will investigate with several models with the urls pulled from the web to test the new models.

### 1.3.2 Train/Val Split from CSV Data

In this section, we train the logistic regression model with the 80/20 split of train/validation with the given csv file.
"""

# Validation split with the train csv
news_copied_df = news_df.copy()

X = news_copied_df["headline"]
y = (news_copied_df["source"] != "fox").astype(int)  # 0=fox,1=nbc

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# fit the baseline Logistic Regression model

# Baseline vectorizer
baseline_vec = TfidfVectorizer(stop_words='english', max_features=100)

# Fit on TRAIN only
X_train_vec = baseline_vec.fit_transform(X_train)
X_val_vec   = baseline_vec.transform(X_val)

# Baseline Logistic Regression
baseline_lr = LogisticRegression(max_iter=100)
baseline_lr.fit(X_train_vec, y_train)

# Evaluate on VALIDATION
y_val_pred = baseline_lr.predict(X_val_vec)
evaluate_model("Baseline", baseline_lr, y_val, y_val_pred)